# Generated by Django 6.0.5 on 2026-07-20 18:00

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="expire_after_n_download",
            field=models.BigIntegerField(
                validators=[apps.files.models.validate_download_count]
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.BigIntegerField(
                validators=[apps.files.models.validate_max_file_size]
            ),
        ),
    ]
