# Generated by Django 6.0.7 on 2026-08-01 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_expire_after_n_download_alter_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('host_token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('expire_after_n_download', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=1024)),
                ('filename', models.CharField(max_length=500)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.room')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_token', models.CharField(max_length=64)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='files.room')),
            ],
            options={
                'unique_together': {('room', 'host_token')},
            },
        ),
    ]
