# Generated by Django 6.0.5 on 2026-10-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_expire_after_n_download_alter_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='chunk_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
