# Generated by Django 6.0.5 on 2026-07-20 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=1024)),
                ('filename', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('expire_after_n_download', models.BigIntegerField()),
                ('download_count', models.BigIntegerField(default=0)),
                ('size', models.BigIntegerField()),
                ('number_of_files', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
