[project]
name = "chithi-backend"
version = "0.1.0"
description = "Chithi Django + Strawberry-Django GraphQL backend"
requires-python = ">=3.13"
dependencies = [
    # Base Framework
    "django[argon2]>=6.0",
    # Database
    "psycopg[binary]>=3",
    # GraphQL
    "strawberry-graphql>=0.322.0",
    "strawberry-graphql-django>=0.86.0",
    # Rest api
    "django-ninja>=1.7.1",
    # JWT
    "PyJWT>=2.10.0",
    # Cors
    "django-cors-headers>=4.7.0",
    # Env loading
    "python-dotenv>=1.2.2",
    # S3 handling
    "boto3>=1.37",
    # File uploading
    "python-multipart>=0.0.18",
    # Database env handling
    "dj-database-url>=3.1.2",
    "django-storages[s3]>=1.14.6",
    # Task runner
    "celery[redis]>=5.4",
    # Redis
    "redis[hiredis]>=6.4.0",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.0.0",
    "django-extensions>=4.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-django>=4.14.0",
    "ruff>=0.12.12",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
python_files = ["test_*.py", "tests.py"]
pythonpath = ["."]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["apps", "core", "tests"]
