# Generated by Django 6.0.5 on 2026-07-20 17:56

import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_storage_limit', models.BigIntegerField(default=10737418240)),
                ('max_file_size_limit', models.BigIntegerField(default=104857600)),
                ('default_expiry', models.BigIntegerField(default=604800)),
                ('default_number_of_downloads', models.IntegerField(default=10)),
                ('site_description', models.TextField(default='Secure file sharing service')),
                ('download_configs', models.JSONField(blank=True, default=list)),
                ('time_configs', models.JSONField(blank=True, default=list)),
                ('allowed_file_types', models.JSONField(blank=True, default=list)),
                ('banned_file_types', models.JSONField(blank=True, default=list)),
                ('allow_uploads', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
