FROM node:25-alpine AS builder
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build:static
RUN npm prune --production

# Dockerfile to serve the static build with lighttpd on Alpine
FROM alpine:3.19
RUN apk add --no-cache lighttpd
WORKDIR /app
COPY build/ build/
COPY lighttpd.conf /etc/lighttpd/lighttpd.conf
EXPOSE 3000
CMD ["lighttpd", "-D", "-f", "/etc/lighttpd/lighttpd.conf"]
