"""Add Size information on files

Revision ID: 0174c68460fd
Revises: b0f939de9dcb
Create Date: 2026-01-17 15:21:59.784458

"""

from typing import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0174c68460fd"
down_revision: str | Sequence[str] | None = "b0f939de9dcb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("size", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "size")
    # ### end Alembic commands ###
