"""update configs

Revision ID: 06f5394139b5
Revises: 6d1b8bb8ce78
Create Date: 2025-12-22 16:07:56.686452

"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "06f5394139b5"
down_revision: str | Sequence[str] | None = "6d1b8bb8ce78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "config",
        sa.Column("download_configs", postgresql.ARRAY(sa.Integer()), nullable=True),
    )
    op.add_column(
        "config", sa.Column("time_configs", postgresql.ARRAY(sa.Date()), nullable=True)
    )
    op.add_column(
        "config",
        sa.Column("allowed_file_types", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "config",
        sa.Column("banned_file_types", postgresql.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("config", "banned_file_types")
    op.drop_column("config", "allowed_file_types")
    op.drop_column("config", "time_configs")
    op.drop_column("config", "download_configs")
    # ### end Alembic commands ###
