"""Change to BigInteger

Revision ID: 8d12371fc44b
Revises: 0174c68460fd
Create Date: 2026-01-28 23:50:41.499635

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d12371fc44b"
down_revision: str | Sequence[str] | None = "0174c68460fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file", "size", existing_type=sa.INTEGER(), type_=sa.BigInteger(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file",
        "size",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
