"""empty message

Revision ID: b0f939de9dcb
Revises: dfb12aeef438
Create Date: 2026-01-01 00:20:17.410265

"""

from typing import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0f939de9dcb"
down_revision: str | Sequence[str] | None = "dfb12aeef438"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file", sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.create_unique_constraint(None, "file", ["id", "key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "file", type_="unique")
    op.drop_column("file", "key")
    # ### end Alembic commands ###
