"""Change to download_count BigInteger

Revision ID: f6bd9eb9dd41
Revises: 8d12371fc44b
Create Date: 2026-01-28 23:51:41.756366

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6bd9eb9dd41"
down_revision: str | Sequence[str] | None = "8d12371fc44b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file",
        "download_count",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file",
        "download_count",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
