[package]
name = "wasm_bindings"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chithi-core = { workspace = true }
sevenz-rust2 = { workspace = true, features = ["aes256_wasm"] }
getrandom = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }
