/**
 * Type declarations for the WASM bindings generated by wasm-bindgen.
 * These match the functions exposed by core/crates/wasm_bindings/
 */

declare namespace WasmBindings {
  // SDK-level
  function upload(
    names: string[],
    datas: Uint8Array[],
    password: string
  ): Uint8Array;

  function download(
    bundle: Uint8Array,
    password: string
  ): Array<{ name: string; data: Uint8Array }>;

  function uploadData(data: Uint8Array, password: string): string;

  function downloadData(bundleJson: string, password: string): Uint8Array;

  // 7z compression
  function validate_7z(data: Uint8Array): boolean;

  function compress_7z(
    names: string[],
    datas: Uint8Array[],
    password: string
  ): Uint8Array;

  function decompress_7z(
    data: Uint8Array,
    password: string
  ): Array<{ name: string; data: Uint8Array }>;

  // Key derivation
  function generate_secret(): string;

  function generate_ikm(): Uint8Array;

  function derive_key(password: Uint8Array, salt: Uint8Array): Uint8Array;

  function argon2_derive(
    password: Uint8Array,
    salt: Uint8Array,
    iterations: number,
    memoryCostKib: number,
    hashLength: number
  ): Uint8Array;

  // Record encryption (AES-256-CBC)
  function encrypt_record(data: Uint8Array, key: Uint8Array): Uint8Array;

  function decrypt_record(data: Uint8Array, key: Uint8Array): Uint8Array;

  // Chunk encryption (AES-256-GCM)
  function encrypt_chunk(
    data: Uint8Array,
    key: Uint8Array,
    nonce: Uint8Array
  ): Uint8Array;

  function decrypt_chunk(
    data: Uint8Array,
    key: Uint8Array,
    nonce: Uint8Array
  ): Uint8Array;

  function get_chunk_nonce(baseIv: Uint8Array, chunkIndex: number): Uint8Array;

  // Batch operations
  function encrypt_chunks_parallel(
    chunks: Uint8Array[],
    key: Uint8Array,
    baseIv: Uint8Array
  ): Uint8Array[];

  function decrypt_chunks_parallel(
    chunks: Uint8Array[],
    key: Uint8Array,
    baseIv: Uint8Array
  ): Uint8Array[];

  function encrypt_all(records: Uint8Array[], key: Uint8Array): Uint8Array[];

  function decrypt_all(records: Uint8Array[], key: Uint8Array): Uint8Array[];

  // Keychain class
  class WasmKeychain {
    constructor();

    static fromPassword(password: string): WasmKeychain;

    setPassword(password: string): void;
    generateSecret(): string;
    encryptMetadata(metadata: string): Uint8Array;
    decryptMetadata(data: Uint8Array): string;
    sign(data: Uint8Array): Uint8Array;
    verify(data: Uint8Array, signature: Uint8Array): boolean;
    exportAuthKey(): Uint8Array;
    salt(): Uint8Array;
    ikm(): Uint8Array;
  }

  // Rayon init for Web Worker parallelism
  function init_threadpool(numWorkers?: number): void;
}

export {};
